GET http://localhost:3003/api/blogs/5cfdf98d8c13c21bacbe9243

###
// The Authorization token must be updated every once in a while using the login.rest request model
DELETE http://localhost:3003/api/blogs/5cfdf98d8c13c21bacbe9243
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RpIiwiaWQiOiI1Y2ZkNjE4Mzg4ODRkYzhkOGNiMTNlMWMiLCJpYXQiOjE1NjAxNTY1Nzl9.5AIaIcfnvuV15i_bOAXawHMsM5cvb0w9mxP54PTbZs0